# Generated by Django 2.1.7 on 2019-03-18 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_chapter_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='chapter',
            field=models.IntegerField(max_length=4),
        ),
    ]
