# Generated by Django 2.1.7 on 2019-03-19 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190318_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextended',
            name='chapter',
            field=models.CharField(blank=True, choices=[('33', '33'), ('30', '30'), ('31', '31'), ('35', '35'), ('1606', '1606')], max_length=4),
        ),
    ]
