# Generated by Django 2.1.7 on 2019-04-01 22:04

import django.core.validators
from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20190321_1057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userextended',
            name='Conc_stud_sched',
        ),
        migrations.RemoveField(
            model_name='userextended',
            name='Resid_tuit_app',
        ),
        migrations.AddField(
            model_name='userextended',
            name='conc_stud_sched',
            field=models.FileField(blank=True, null=True, upload_to=users.models.UserExtended.user_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AddField(
            model_name='userextended',
            name='resid_tuit_app',
            field=models.FileField(blank=True, null=True, upload_to=users.models.UserExtended.user_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AlterField(
            model_name='userextended',
            name='MVP_info_sheet',
            field=models.FileField(blank=True, null=True, upload_to=users.models.UserExtended.user_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AlterField(
            model_name='userextended',
            name='cert_of_elig',
            field=models.FileField(blank=True, null=True, upload_to=users.models.UserExtended.user_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AlterField(
            model_name='userextended',
            name='star_deg_audit',
            field=models.FileField(blank=True, null=True, upload_to=users.models.UserExtended.user_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AlterField(
            model_name='userextended',
            name='stud_respon',
            field=models.FileField(blank=True, null=True, upload_to=users.models.UserExtended.user_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
