# Generated by Django 2.1.7 on 2019-04-01 23:54

from django.db import migrations, models
import django.utils.timezone
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20190401_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextended',
            name='cert_of_elig',
            field=models.FileField(blank=True, default=django.utils.timezone.now, upload_to=users.models.UserExtended.user_directory_path),
            preserve_default=False,
        ),
    ]
