# Generated by Django 2.1.7 on 2019-04-02 00:17

import django.core.validators
from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20190401_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextended',
            name='cert_of_elig',
            field=models.FileField(blank=True, null=True, upload_to=users.models.UserExtended.user_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
