# Generated by Django 2.1.7 on 2019-04-02 02:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20190401_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextended',
            name='cert_of_elig',
            field=models.FileField(blank=True, null=True, upload_to='profile_pics', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
