# Generated by Django 2.1.7 on 2019-04-02 03:13

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20190401_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextended',
            name='cert_of_elig',
            field=models.FileField(blank=True, default=django.utils.timezone.now, upload_to=users.models.UserExtended.user_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
            preserve_default=False,
        ),
    ]
