# Generated by Django 2.1.7 on 2019-04-08 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_userextended_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextended',
            name='carrier',
            field=models.CharField(blank=True, choices=[('AT&T', 'AT&T'), ('Verizon', 'Verizon'), ('Sprint', 'Sprint'), ('T-Mobile', 'T-Mobile'), ('Virgin', 'Virgin')], max_length=15),
        ),
    ]
