# Generated by Django 2.1.7 on 2019-04-09 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_userextended_carrier'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextended',
            name='phone_notifications',
            field=models.BooleanField(default=False),
        ),
    ]
