# Generated by Django 2.1.7 on 2019-04-28 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_userextended_phone_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextended',
            name='progress_student',
            field=models.IntegerField(default=0),
        ),
    ]
