# Generated by Django 2.1.7 on 2019-04-09 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_chapter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='chapter',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='student',
        ),
        migrations.AddField(
            model_name='post',
            name='Certificate_of_eligibility',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='Concise_student_schedule',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='MVP_information_sheet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='Resident_tuition_app',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='Star_degree_audit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='Student_responsibility',
            field=models.BooleanField(default=False),
        ),
    ]
