# Generated by Django 2.1.7 on 2019-04-09 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20190408_2013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='date_posted',
            new_name='date_certified',
        ),
    ]
