# Generated by Django 2.1.7 on 2019-04-09 03:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20190408_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date_began',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_certified',
            field=models.DateTimeField(),
        ),
    ]
