# Generated by Django 2.1.7 on 2019-04-09 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20190408_2106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='date_certified',
        ),
    ]
