# Generated by Django 2.1.7 on 2019-04-14 06:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20190413_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certs', to=settings.AUTH_USER_MODEL),
        ),
    ]
