# Generated by Django 2.1.7 on 2019-04-22 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20190414_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='last_certifier',
            field=models.CharField(default='None', max_length=80),
        ),
    ]
