# Generated by Django 2.1.7 on 2019-04-24 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_auto_20190422_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='progress',
            field=models.IntegerField(default=0),
        ),
    ]
