# Generated by Django 2.1.7 on 2019-04-28 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_post_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='CertifiedBy',
            field=models.CharField(default='None(COE)', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='CertifiedBy2',
            field=models.CharField(default='None(Info Sheet)', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='CertifiedBy3',
            field=models.CharField(default='None(Student Responsibility)', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='CertifiedBy4',
            field=models.CharField(default='None(Date Tuition)', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='CertifiedBy5',
            field=models.CharField(default='None(Concise Student Schedule)', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='CertifiedBy6',
            field=models.CharField(default='None(Degree Audit)', max_length=20),
        ),
    ]
